### ISSUE TITLE
Instructions somewhat unclear for certificate/attestation creation

### ISSUE THREAD

**Issue by alphathegeek** [Crystalix007/U2FDevice#3]
xxd --include certificate.pem -- file not found, perhaps this refers to server.pem?

somewhat unclear.

**Comment by alphathegeek** [comment]
Awesome! Thanks for the Readme updates and the other patches. I'd have done
a pull request, but I figure these were easy to close. Great project. I ran
the yubikey demo app and it passes, going to try it on google next. I have
an application in mind as a backup key for this, and your project fit the
need perfectly.

solokey which also can use the Pi, seems to have some problems with u2f,
specifically gmail/google.

-A Happy Pi-Zero User

**Comment by Crystalix007** [comment]
Thanks for taking the time to check the project out. Thanks for also spotting these issues - you probably saved me quite some time, specifically with debugging the `#ifdef` issue.
